VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Site"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Public Site          As String
Public SiteDesc      As String
Public ProjectCode   As String
Public ProjectDesc   As String
Public SiteLocation  As String
Public SiteElevation As Single
Public Latitude      As String
Public Longitude     As String
Public TimeOffset    As String

