VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "WT"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Public height As Double

Public r10 As Object
Public r60 As Object
Public rt10 As Object
Public rt60 As Object
Public rs10 As Object
Public rs60 As Object
Public c60 As Double
Public c10 As Double

'Public cn As String ' wt 列名
'Public tn As String ' time 列名

